import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  french('Français', 'French', 'fr', 'fr_FR', false),
  arabic('العربية', 'Arabic', 'ar', 'ar_SA', true),
  english('English', 'English', 'en', 'en_US', false),
  ukrainian('Українська', 'Ukrainian', 'uk', 'uk_UA', false),
  italian('Italiano', 'Italian', 'it', 'it_IT', false),
  eritrean('ትግርኛ', 'Tigrinya', 'ti', 'ti_ER', false),
  turkish('Türkçe', 'Turkish', 'tr', 'tr_TR', false),
  indonesian('Bahasa Indonesia', 'Indonesian', 'id', 'id_ID', false);

  final String name;
  final String englishName;
  final String code;
  final String ttsCode;
  final bool isRTL;

  const AppLanguage(this.name, this.englishName, this.code, this.ttsCode, this.isRTL);
}

class LanguageProvider extends ChangeNotifier {
  AppLanguage _currentLanguage = AppLanguage.english;
  static const String _prefKey = 'selected_language';

  LanguageProvider() {
    debugPrint("🌐 LanguageProvider initialized");
    _loadLanguage();
  }

  AppLanguage get currentLanguage => _currentLanguage;
  bool get isRTL => _currentLanguage.isRTL;

  Future<void> _loadLanguage() async {
    try {
      debugPrint("🌐 Loading language from prefs...");
      final prefs = await SharedPreferences.getInstance();
      final savedCode = prefs.getString(_prefKey);
      if (savedCode != null) {
        _currentLanguage = AppLanguage.values.firstWhere(
          (l) => l.code == savedCode,
          orElse: () => AppLanguage.english,
        );
        notifyListeners();
      }
      debugPrint("🌐 Language loaded: ${_currentLanguage.code}");
    } catch (e) {
      debugPrint("🌐 Language load error: $e");
    }
  }

  Future<void> setLanguage(AppLanguage language) async {
    if (_currentLanguage == language) return;
    _currentLanguage = language;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, language.code);
  }

  // Helper for basic UI strings
  String translate(String key) {
    // This is a simple mapper for core UI strings that don't need AI
    final translations = {
      'en': {
        'greeting': 'Bonjour!',
        'subtitle': 'What would you like to master today?',
        'grammar': 'Grammar',
        'exercises': 'Exercises',
        'flashcards': 'Flashcards',
        'lessons': 'Lessons',
        'verbs': 'Verbs',
        'examen': 'Examen',
        'examen_desc': 'B1 Final Evaluation',
        'essays': 'Essays',
        'dialogues': 'Dialogues',
        'daily_phrases': 'Daily Phrases',
        'listening': 'Listening',
        'vocabulary': 'Vocabulary',
        'vocab_desc': 'Words & English look-alikes',
        'expressions': 'Expressions',
        'expressions_desc': 'Speak like a local',
        'street_french': 'Street French',
        'street_desc': 'Slang & Belgian French',
        'tab_today': 'Today',
        'tab_learn': 'Learn',
        'tab_practice': 'Practise',
        'tab_words': 'Words',
        'tab_me': 'Me',
        'reviews': 'Reviews',
        'conj_game': 'Conjugation game',
        'dictee': 'Dictation',
        'roleplay': 'Role-play in Belgium',
        'duel': 'Duel with a friend',
        'mistakes': 'My mistakes',
        'photo_words': 'Photo → words',
        'missions': 'Missions of the week',
        'my_words': 'My words',
        'word_of_day': 'Word of the day',
        'daily_goal': 'Daily goal',
        'streak': 'days in a row',
        'start_now': "Let's go!",
        'cards_to_review': 'cards to review',
        'all_reviewed': 'All reviews done',
        'continue_story': 'Continue your story',
        'quick_play': 'Quick practice',
        'my_progress': 'My progress',
        'total_xp': 'Total XP',
        'words_learned': 'Words learned',
        'active_days': 'Active days',
        'this_week': 'This week',
        'settings': 'Settings',
        'app_language': 'Language of explanations',
        'install_app': 'Install the app',
        'grammar_lessons': 'Grammar',
        'select_language': 'Select Language',
        'ai_book': 'AI Story Book',
        'ai_book_desc': 'Interactive tales',
        'culture_vocab': 'Culture & Vocab',
        'daily_practice': 'Daily practice',
        'master_rules': 'Master the rules',
        'memorize_smart': 'Memorize smart',
        'conjugations': 'Conjugations',
        'common_talk': 'Common talk',
        'audio_skills': 'Audio skills',
        'ai_novelist': 'AI Novelist',
        'writing_novel': 'Professeur AI is writing your novel...',
        'building_story': 'Building an immersive story...',
        'create_magic_story': 'Create Your Magic Story ✨',
        'pick_topics': 'Pick your favorite grammar and vocabulary topics.',
        'grammar_to_use': 'Grammar to Use',
        'vocab_focus': 'Vocabulary Focus',
        'create_my_novel': 'Create My Novel',
        'learning_points': 'Learning Points',
        'new_story': 'New Story',
        'page': 'Page',
        'of': 'of',
        'select_topic_error': 'Please select at least one topic!',
        'neural_voice': 'Neural Voice',
        'system_voice': 'System Voice',
        'error': 'Error',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
      'fr': {
        'greeting': 'Bonjour!',
        'subtitle': 'Que voulez-vous apprendre aujourd\'hui ?',
        'grammar': 'Grammaire',
        'exercises': 'Exercices',
        'flashcards': 'Cartes mémoire',
        'lessons': 'Leçons',
        'verbs': 'Verbes',
        'examen': 'Examen',
        'examen_desc': 'Évaluation finale B1',
        'essays': 'Rédactions',
        'dialogues': 'Dialogues',
        'daily_phrases': 'Phrases quotidiennes',
        'listening': 'Écoute',
        'vocabulary': 'Vocabulaire',
        'vocab_desc': 'Mots et mots transparents',
        'expressions': 'Expressions',
        'expressions_desc': 'Parler comme un local',
        'street_french': 'Français de la rue',
        'street_desc': 'Argot et belgicismes',
        'tab_today': "Aujourd'hui",
        'tab_learn': 'Apprendre',
        'tab_practice': 'Pratiquer',
        'tab_words': 'Mots',
        'tab_me': 'Moi',
        'reviews': 'Révisions',
        'conj_game': 'Jeu de conjugaison',
        'dictee': 'Dictée',
        'roleplay': 'Jeu de rôle belge',
        'duel': 'Duel entre amis',
        'mistakes': 'Mes erreurs',
        'photo_words': 'Photo → mots',
        'missions': 'Missions de la semaine',
        'my_words': 'Mes mots',
        'word_of_day': 'Le mot du jour',
        'daily_goal': 'Objectif du jour',
        'streak': 'jours de suite',
        'start_now': "C'est parti !",
        'cards_to_review': 'cartes à revoir',
        'all_reviewed': 'Révisions terminées',
        'continue_story': 'Continue ton histoire',
        'quick_play': 'Entraînement rapide',
        'my_progress': 'Ma progression',
        'total_xp': 'XP total',
        'words_learned': 'Mots appris',
        'active_days': 'Jours actifs',
        'this_week': 'Cette semaine',
        'settings': 'Réglages',
        'app_language': 'Langue des explications',
        'install_app': "Installer l'application",
        'grammar_lessons': 'Grammaire',
        'select_language': 'Choisir la langue',
        'ai_book': 'Livre de contes IA',
        'ai_book_desc': 'Contes interactifs',
        'culture_vocab': 'Culture & Vocab',
        'daily_practice': 'Pratique quotidienne',
        'master_rules': 'Maîtriser les règles',
        'memorize_smart': 'Mémoriser intelligemment',
        'conjugations': 'Conjugaisons',
        'common_talk': 'Conversations courantes',
        'audio_skills': 'Compétences audio',
        'ai_novelist': 'Romancier IA',
        'writing_novel': 'Professeur IA écrit votre roman...',
        'building_story': 'Création d\'une histoire immersive...',
        'create_magic_story': 'Créez votre histoire magique ✨',
        'pick_topics': 'Choisissez vos thèmes préférés.',
        'grammar_to_use': 'Grammaire à utiliser',
        'vocab_focus': 'Focus vocabulaire',
        'create_my_novel': 'Créer mon roman',
        'learning_points': 'Points d\'apprentissage',
        'new_story': 'Nouvelle histoire',
        'page': 'Page',
        'of': 'sur',
        'select_topic_error': 'Veuillez sélectionner au moins un sujet !',
        'neural_voice': 'Voix Neurale',
        'system_voice': 'Voix Système',
        'error': 'Erreur',
        'admin_ai': 'Assistant IA Admin 🔒',
        'admin_ai_desc': 'Boîte IA privée',
      },
      'ar': {
        'greeting': 'مرحباً!',
        'subtitle': 'ماذا تود أن تتعلم اليوم؟',
        'grammar': 'القواعد',
        'exercises': 'تمارين',
        'flashcards': 'بطاقات تعليمية',
        'lessons': 'دروس',
        'verbs': 'الأفعال',
        'examen': 'امتحان',
        'examen_desc': 'التقييم النهائي B1',
        'essays': 'مقالات',
        'dialogues': 'حوارات',
        'daily_phrases': 'جمل يومية',
        'listening': 'استماع',
        'vocabulary': 'المفردات',
        'vocab_desc': 'كلمات وكلمات تشبه الإنجليزية',
        'expressions': 'التعابير',
        'expressions_desc': 'تكلّم مثل أهل البلد',
        'street_french': 'فرنسية الشارع',
        'street_desc': 'العامية والفرنسية البلجيكية',
        'tab_today': 'اليوم',
        'tab_learn': 'تعلّم',
        'tab_practice': 'تدرّب',
        'tab_words': 'الكلمات',
        'tab_me': 'أنا',
        'reviews': 'المراجعات',
        'conj_game': 'لعبة التصريف',
        'dictee': 'الإملاء',
        'roleplay': 'لعب أدوار في بلجيكا',
        'duel': 'مبارزة مع صديق',
        'mistakes': 'أخطائي',
        'photo_words': 'صورة ← كلمات',
        'missions': 'مهام الأسبوع',
        'my_words': 'كلماتي',
        'word_of_day': 'كلمة اليوم',
        'daily_goal': 'هدف اليوم',
        'streak': 'أيام متتالية',
        'start_now': 'لنبدأ!',
        'cards_to_review': 'بطاقات للمراجعة',
        'all_reviewed': 'انتهت المراجعات',
        'continue_story': 'تابع قصتك',
        'quick_play': 'تدريب سريع',
        'my_progress': 'تقدّمي',
        'total_xp': 'مجموع النقاط',
        'words_learned': 'كلمات محفوظة',
        'active_days': 'أيام النشاط',
        'this_week': 'هذا الأسبوع',
        'settings': 'الإعدادات',
        'app_language': 'لغة الشرح',
        'install_app': 'تثبيت التطبيق',
        'grammar_lessons': 'القواعد',
        'select_language': 'اختر اللغة',
        'ai_book': 'كتاب القصص الذكي',
        'ai_book_desc': 'قصص تفاعلية',
        'culture_vocab': 'الثقافة والمفردات',
        'daily_practice': 'ممارسة يومية',
        'master_rules': 'إتقان القواعد',
        'memorize_smart': 'حفظ بذكاء',
        'conjugations': 'تصريف الأفعال',
        'common_talk': 'محادثات شائعة',
        'audio_skills': 'مهارات الاستماع',
        'ai_novelist': 'روائي الذكاء الاصطناعي',
        'writing_novel': 'البروفيسور الذكي يكتب روايتك...',
        'building_story': 'بناء قصة غامرة بمواضيعك...',
        'create_magic_story': 'أنشئ قصتك السحرية ✨',
        'pick_topics': 'اختر مواضيع القواعد والمفردات المفضلة لديك.',
        'grammar_to_use': 'القواعد المستخدمة',
        'vocab_focus': 'تركيز المفردات',
        'create_my_novel': 'أنشئ روايتي',
        'learning_points': 'نقاط التعلم',
        'new_story': 'قصة جديدة',
        'page': 'صفحة',
        'of': 'من',
        'select_topic_error': 'يرجى اختيار موضوع واحد على الأقل!',
        'neural_voice': 'صوت عصبي (ممتاز)',
        'system_voice': 'صوت النظام',
        'error': 'خطأ',
        'admin_ai': 'مساعد الذكاء الاصطناعي للمشرف 🔒',
        'admin_ai_desc': 'صندوق ذكاء اصطناعي خاص',
      },
      'uk': {
        'greeting': 'Привіт!',
        'subtitle': 'Що б ви хотіли вивчити сьогодні?',
        'grammar': 'Граматика',
        'exercises': 'Вправи',
        'flashcards': 'Картки',
        'lessons': 'Уроки',
        'verbs': 'Дієслова',
        'examen': 'Іспит',
        'examen_desc': 'Підсумковий іспит B1',
        'essays': 'Твори',
        'dialogues': 'Діалоги',
        'daily_phrases': 'Щоденні фрази',
        'listening': 'Слухання',
        'vocabulary': 'Словник',
        'vocab_desc': 'Слова та схожі англійські слова',
        'expressions': 'Вирази',
        'expressions_desc': 'Говори як місцевий',
        'street_french': 'Вулична французька',
        'street_desc': 'Сленг і бельгійська французька',
        'tab_today': 'Сьогодні',
        'tab_learn': 'Вчити',
        'tab_practice': 'Практика',
        'tab_words': 'Слова',
        'tab_me': 'Я',
        'reviews': 'Повторення',
        'conj_game': 'Гра відмінювання',
        'dictee': 'Диктант',
        'roleplay': 'Рольова гра',
        'duel': 'Дуель з другом',
        'mistakes': 'Мої помилки',
        'photo_words': 'Фото → слова',
        'missions': 'Місії тижня',
        'my_words': 'Мої слова',
        'word_of_day': 'Слово дня',
        'daily_goal': 'Ціль дня',
        'streak': 'днів поспіль',
        'start_now': 'Почнімо!',
        'cards_to_review': 'карток для повторення',
        'all_reviewed': 'Усе повторено',
        'continue_story': 'Продовжуй історію',
        'quick_play': 'Швидка практика',
        'my_progress': 'Мій прогрес',
        'total_xp': 'Усього XP',
        'words_learned': 'Вивчені слова',
        'active_days': 'Активні дні',
        'this_week': 'Цього тижня',
        'settings': 'Налаштування',
        'app_language': 'Мова пояснень',
        'install_app': 'Встановити додаток',
        'grammar_lessons': 'Граматика',
        'select_language': 'Оберіть мову',
        'ai_book': 'AI Story Book',
        'ai_book_desc': 'Interactive tales',
        'culture_vocab': 'Culture & Vocab',
        'daily_practice': 'Daily practice',
        'master_rules': 'Master the rules',
        'memorize_smart': 'Memorize smart',
        'conjugations': 'Conjugations',
        'common_talk': 'Common talk',
        'audio_skills': 'Audio skills',
        'ai_novelist': 'AI Novelist',
        'writing_novel': 'Professeur AI is writing your novel...',
        'building_story': 'Building an immersive story...',
        'create_magic_story': 'Create Your Magic Story ✨',
        'pick_topics': 'Pick your favorite grammar and vocabulary topics.',
        'grammar_to_use': 'Grammar to Use',
        'vocab_focus': 'Vocabulary Focus',
        'create_my_novel': 'Create My Novel',
        'learning_points': 'Learning Points',
        'new_story': 'New Story',
        'page': 'Page',
        'of': 'of',
        'select_topic_error': 'Please select at least one topic!',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
      'it': {
        'greeting': 'Buongiorno!',
        'subtitle': 'Cosa ti piacerebbe imparare oggi?',
        'grammar': 'Grammatica',
        'exercises': 'Esercizi',
        'flashcards': 'Flashcard',
        'lessons': 'Lezioni',
        'verbs': 'Verbi',
        'examen': 'Esame',
        'examen_desc': 'Valutazione finale B1',
        'essays': 'Saggi',
        'dialogues': 'Dialoghi',
        'daily_phrases': 'Frasi quotidiane',
        'listening': 'Ascolto',
        'vocabulary': 'Vocabolario',
        'vocab_desc': "Parole e somiglianze con l'inglese",
        'expressions': 'Espressioni',
        'expressions_desc': 'Parla come un locale',
        'street_french': 'Francese di strada',
        'street_desc': 'Slang e francese belga',
        'tab_today': 'Oggi',
        'tab_learn': 'Impara',
        'tab_practice': 'Pratica',
        'tab_words': 'Parole',
        'tab_me': 'Io',
        'reviews': 'Ripasso',
        'conj_game': 'Gioco di coniugazione',
        'dictee': 'Dettato',
        'roleplay': 'Gioco di ruolo',
        'duel': 'Sfida con un amico',
        'mistakes': 'I miei errori',
        'photo_words': 'Foto → parole',
        'missions': 'Missioni della settimana',
        'my_words': 'Le mie parole',
        'word_of_day': 'Parola del giorno',
        'daily_goal': 'Obiettivo del giorno',
        'streak': 'giorni di fila',
        'start_now': 'Andiamo!',
        'cards_to_review': 'carte da ripassare',
        'all_reviewed': 'Ripasso finito',
        'continue_story': 'Continua la tua storia',
        'quick_play': 'Pratica veloce',
        'my_progress': 'I miei progressi',
        'total_xp': 'XP totali',
        'words_learned': 'Parole imparate',
        'active_days': 'Giorni attivi',
        'this_week': 'Questa settimana',
        'settings': 'Impostazioni',
        'app_language': 'Lingua delle spiegazioni',
        'install_app': "Installa l'app",
        'grammar_lessons': 'Grammatica',
        'select_language': 'Seleziona lingua',
        'ai_book': 'AI Story Book',
        'ai_book_desc': 'Interactive tales',
        'culture_vocab': 'Culture & Vocab',
        'daily_practice': 'Daily practice',
        'master_rules': 'Master the rules',
        'memorize_smart': 'Memorize smart',
        'conjugations': 'Conjugations',
        'common_talk': 'Common talk',
        'audio_skills': 'Audio skills',
        'ai_novelist': 'AI Novelist',
        'writing_novel': 'Professeur AI is writing your novel...',
        'building_story': 'Building an immersive story...',
        'create_magic_story': 'Create Your Magic Story ✨',
        'pick_topics': 'Pick your favorite grammar and vocabulary topics.',
        'grammar_to_use': 'Grammar to Use',
        'vocab_focus': 'Vocabulary Focus',
        'create_my_novel': 'Create My Novel',
        'learning_points': 'Learning Points',
        'new_story': 'New Story',
        'page': 'Page',
        'of': 'of',
        'select_topic_error': 'Please select at least one topic!',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
      'ti': {
        'greeting': 'ሰላም!',
        'subtitle': 'ሎሚ እንታይ ክትመሃር ትደሊ?',
        'grammar': 'ሰዋስው',
        'exercises': 'ልምምድ',
        'flashcards': 'ፍላሽካርድ',
        'lessons': 'ትምህርቲ',
        'verbs': 'ግስታት',
        'examen': 'ፈተና',
        'examen_desc': 'ናይ መወዳእታ ገምጋም B1',
        'essays': 'ጽሑፋት',
        'dialogues': 'ምልልስ',
        'daily_phrases': 'መዓልታዊ ሓረጋት',
        'listening': 'ምስማዕ',
        'vocabulary': 'ቃላት',
        'vocab_desc': 'ቃላትን ምስ እንግሊዝኛ ዝመሳሰሉን',
        'expressions': 'መግለጺታት',
        'expressions_desc': 'ከም ተወላዲ ተዛረብ',
        'street_french': 'ፈረንሳይኛ ጎደና',
        'street_desc': 'ስላንግን ቤልጂካዊ ፈረንሳይኛን',
        'tab_today': 'ሎሚ',
        'tab_learn': 'ተማሃር',
        'tab_practice': 'ተለማመድ',
        'tab_words': 'ቃላት',
        'tab_me': 'ኣነ',
        'grammar_lessons': 'ሰዋስው',
        'select_language': 'ቋንቋ ምረጽ',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
      'tr': {
        'greeting': 'Merhaba!',
        'subtitle': 'Bugün ne öğrenmek istersin?',
        'grammar': 'Dilbilgisi',
        'exercises': 'Alıştırmalar',
        'flashcards': 'Bilgi Kartları',
        'lessons': 'Dersler',
        'verbs': 'Fiiller',
        'examen': 'Sınav',
        'examen_desc': 'B1 Final Değerlendirmesi',
        'essays': 'Kompozisyonlar',
        'dialogues': 'Diyaloglar',
        'daily_phrases': 'Günlük Kalıplar',
        'listening': 'Dinleme',
        'vocabulary': 'Kelime Bilgisi',
        'vocab_desc': 'Kelimeler ve İngilizceye benzeyenler',
        'expressions': 'Deyimler',
        'expressions_desc': 'Yerli gibi konuş',
        'street_french': 'Sokak Fransızcası',
        'street_desc': 'Argo ve Belçika Fransızcası',
        'tab_today': 'Bugün',
        'tab_learn': 'Öğren',
        'tab_practice': 'Pratik',
        'tab_words': 'Kelimeler',
        'tab_me': 'Ben',
        'reviews': 'Tekrar',
        'conj_game': 'Çekim oyunu',
        'dictee': 'Dikte',
        'roleplay': 'Rol yapma',
        'duel': 'Arkadaşla düello',
        'mistakes': 'Hatalarım',
        'photo_words': 'Fotoğraf → kelimeler',
        'missions': 'Haftanın görevleri',
        'my_words': 'Kelimelerim',
        'word_of_day': 'Günün kelimesi',
        'daily_goal': 'Günlük hedef',
        'streak': 'gün üst üste',
        'start_now': 'Başlayalım!',
        'cards_to_review': 'tekrar kartı',
        'all_reviewed': 'Tekrarlar bitti',
        'continue_story': 'Hikayene devam et',
        'quick_play': 'Hızlı pratik',
        'my_progress': 'İlerlemem',
        'total_xp': 'Toplam XP',
        'words_learned': 'Öğrenilen kelimeler',
        'active_days': 'Aktif günler',
        'this_week': 'Bu hafta',
        'settings': 'Ayarlar',
        'app_language': 'Açıklama dili',
        'install_app': 'Uygulamayı yükle',
        'grammar_lessons': 'Dilbilgisi',
        'select_language': 'Dil Seçin',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
      'id': {
        'greeting': 'Halo!',
        'subtitle': 'Apa yang ingin kamu pelajari hari ini?',
        'grammar': 'Tata Bahasa',
        'exercises': 'Latihan',
        'flashcards': 'Kartu Belajar',
        'lessons': 'Pelajaran',
        'verbs': 'Kata Kerja',
        'examen': 'Ujian',
        'examen_desc': 'Evaluasi Akhir B1',
        'essays': 'Esai',
        'dialogues': 'Dialog',
        'daily_phrases': 'Frasa Harian',
        'listening': 'Mendengarkan',
        'vocabulary': 'Kosakata',
        'vocab_desc': 'Kata dan kemiripan dengan Inggris',
        'expressions': 'Ungkapan',
        'expressions_desc': 'Bicara seperti penduduk lokal',
        'street_french': 'Bahasa Prancis Jalanan',
        'street_desc': 'Slang dan Prancis Belgia',
        'tab_today': 'Hari ini',
        'tab_learn': 'Belajar',
        'tab_practice': 'Latihan',
        'tab_words': 'Kata',
        'tab_me': 'Saya',
        'reviews': 'Ulasan',
        'conj_game': 'Permainan konjugasi',
        'dictee': 'Dikte',
        'roleplay': 'Bermain peran',
        'duel': 'Duel dengan teman',
        'mistakes': 'Kesalahanku',
        'photo_words': 'Foto → kata',
        'missions': 'Misi minggu ini',
        'my_words': 'Kataku',
        'word_of_day': 'Kata hari ini',
        'daily_goal': 'Target harian',
        'streak': 'hari berturut-turut',
        'start_now': 'Ayo mulai!',
        'cards_to_review': 'kartu untuk diulang',
        'all_reviewed': 'Semua sudah diulang',
        'continue_story': 'Lanjutkan ceritamu',
        'quick_play': 'Latihan cepat',
        'my_progress': 'Kemajuanku',
        'total_xp': 'Total XP',
        'words_learned': 'Kata dipelajari',
        'active_days': 'Hari aktif',
        'this_week': 'Minggu ini',
        'settings': 'Pengaturan',
        'app_language': 'Bahasa penjelasan',
        'install_app': 'Pasang aplikasi',
        'grammar_lessons': 'Tata Bahasa',
        'select_language': 'Pilih Bahasa',
        'admin_ai': 'Admin Assistant 🔒',
        'admin_ai_desc': 'Private AI Box',
      },
    };

    return translations[_currentLanguage.code]?[key] ?? translations['en']![key] ?? key;
  }
}
